### ISSUE TITLE
Try to auto-start Steam if it isn't already running

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#143]

**Comment by Sonsalt** [comment]
@sickboy steam does start now but you still get the message, that you have to start it first. It would make sense, to either display a loading message in the tray, "Launching Steam" similar to how we display" the other win notification messages. 

Having the warning message is confusing. I did in fact start Steam manually after that. This was as steam takes some minutes for me to launch here. (1-2 min due to login)

**Comment by sickboy** [comment]
@Sonsalt that's insane. Well we'll have to think about how to handle such special cases.
I think it's fine that it works under usual circumstances, but not when you have to wait minutes for Steam to launch.
