### ISSUE TITLE
Add content source indicator

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#91]
Todo

- [x] Move the icon to the left, when there is no Group icon. It is aligned with the AddToPlaylist button.
- [x] On the horizontal cards (like Stream), move the AddToPlayList button, and the Source Icon to the far left, and the dropdown menu to the far right.
- [x] Add the full text version on the Detail pages.

Feedback / Thoughts / Blurps

- Hover over on Cards on stream overlays the Steam icon
- Steam icon looks too far on the right, especially with the absence of Group content. 
- Grey Background makes the icon looks out of place.

**Comment by sickboy** [comment]
Crude first indicator added. Please provide requirements @Sonsalt

**Comment by Sonsalt** [comment]
@sickboy thanks, the icon shows, now it is all about where and how to place it.

**Comment by Sonsalt** [comment]
@ParaGraphicL please take a look and let us know what you think on where this should show?

**Comment by ParaGraphicL** [comment]
@Sonsalt @sickboy Do we always only have 1 source? Or is it possible as we start aggregating from more sources, that we'd show one mod with multiple mirrors?

Displaying the Steam icon is needed as the user also needs steam to get the content, right? Other sources not so much... so it's more of a "this mod requires steam" if the only source is steam, I guess. 

Now we also have the situation where for an entire game, steam is the only source. Unless authors start uploading to us directly? But showing the Steam logo on all the mods wouldn't really make sense, well it does but could be solved by showing "You need to have a steam account for this game's mods" once, instead of all the time.

But without all of that considered for now. Here is the first design: 
![steamindicators](https://cloud.githubusercontent.com/assets/1974880/17457502/7744b280-5bfa-11e6-9a22-639835d35f46.png)

I've added it to all the other possible items (if only steam icon is shown, place at location of group content icon)

**Comment by Sonsalt** [comment]
@sickboy the new icons are not implemented

**Comment by sickboy** [comment]
@Sonsalt oh rly? but Sven's work is done, and ready for (y)our inspection

**Comment by Sonsalt** [comment]
@ParaGraphicL 

Thanks for your work, we might have other sources in the future, but those might be in most cases privatly hosted (Group content ) elemements, as most pages to live from Advertisement.... However it could be that we link to third party sources for special tools that are required and are only hosted on those pages. 

Since we do encourage hosting content on our side it does make sense to show the steam icon on every mod. The goal is to get users to host with us. 

On a side-note, we could help Authors to do that even if they host on steam, once the content is claimed, they then can simply click on Upload to withSIX and the Steam content will be hosted with us too.... 

Ready for implementation  @sickboy

**Comment by Sonsalt** [comment]
@ParaGraphicL 

Maybe the logo within the icon could be bigger to not look so generic anymore?

**Comment by ParaGraphicL** [comment]
@sickboy 

> (if only steam icon is shown, place [the steam icon] at location of group content icon)

Also make sure the Content page design has all the extra text to it (granted that this is open to change with the new content page design)

**Comment by sickboy** [comment]
> Hover over on Cards on stream overlays the Steam icon

Please speak English and create actionable items.
